name: flutter_test_project
description: Test project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  url_launcher: ^6.1.6
  auto_size_text: ^3.0.0
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.4
  curl_logger_dio_interceptor: ^0.0.3
  dartz: ^0.10.1
  dio: ^4.0.6
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_gen: ^4.2.1
  flutter_svg: ^1.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  injectable: ^1.5.3
  internet_connection_checker: ^0.0.1+4
  intl: ^0.17.0
  json_annotation: ^4.6.0
  location: ^4.4.0
  logger: ^1.1.0
  percent_indicator: ^4.2.2
  retrofit: ^3.0.1+1
  shared_preferences: ^2.0.13
  flutter_screenutil: ^5.5.3+2
  pull_to_refresh: ^2.0.0
  shimmer: ^2.0.0
  jwt_decoder: ^2.0.1
  permission_handler: ^9.2.0
  month_year_picker: ^0.2.0+1
  collection: ^1.15.0
  image_picker: ^0.8.5+3
  http_parser: ^4.0.1
  syncfusion_flutter_datepicker: ^20.2.38
  package_info_plus: ^1.4.3
  store_redirect: ^2.0.1
  table_calendar: ^3.0.6
  dio_cache_interceptor: ^3.3.1

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  flutter_gen_runner: ^4.2.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.5
  retrofit_generator: ^4.0.1
flutter_gen:
  output: lib/presentation/core/utils/generated_assets/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/
